# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlateChecker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PlateChecker

  target 'PlateChecker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlateCheckerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PlateChecker-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PlateChecker-tvOS

  target 'PlateChecker-tvOSTests' do
    inherit! :search_paths
    pod 'react-native-camera', path: '../node_modules/react-native-camera'
    # Pods for testing
  end

end
